"""Concept Store - SQLite-backed storage for canonical concepts and definitions."""

import sqlite3
import json
from typing import List, Optional, Dict, Any

class ConceptStore:
    def __init__(self, connection: sqlite3.Connection):
        self.conn = connection
        self.cursor = self.conn.cursor()
        self._create_table()

    def _create_table(self):
        """Create or migrate the concepts table to the latest schema."""
        self.cursor.execute("""
            CREATE TABLE IF NOT EXISTS concepts (
                id TEXT PRIMARY KEY,
                display_name TEXT,
                definition TEXT,
                metadata TEXT
            )
        """)

        # Schema migration
        self.cursor.execute("PRAGMA table_info(concepts)")
        columns = [info[1] for info in self.cursor.fetchall()]

        if "canonical_name" not in columns:
            print("INFO: Older DB schema detected. Migrating 'concepts' table...")
            self.cursor.execute("ALTER TABLE concepts ADD COLUMN canonical_name TEXT")

        if "expected_data_type" not in columns:
            self.cursor.execute("ALTER TABLE concepts ADD COLUMN expected_data_type TEXT")

        self.cursor.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_canonical_name ON concepts(canonical_name)")
        self.conn.commit()

    def add_concepts_batch(self, concepts: List[Dict[str, Any]]):
        """Batch add or update concepts."""
        if not concepts:
            return

        records = []
        for concept in concepts:
            record = (
                concept.get("id"),
                concept.get("canonical_name"),
                concept.get("display_name"),
                concept.get("data_context", {}).get("typical_datatype"),
                concept.get("definition"),
                json.dumps(concept)
            )
            records.append(record)

        try:
            self.cursor.executemany(
                """INSERT OR REPLACE INTO concepts
                   (id, canonical_name, display_name, expected_data_type, definition, metadata)
                   VALUES (?, ?, ?, ?, ?, ?)""",
                records
            )
            self.conn.commit()
        except sqlite3.Error as e:
            print(f"Error during batch insert into concepts: {e}")
            self.conn.rollback()

    def get_concept_by_id(self, concept_id: str) -> Optional[Dict[str, Any]]:
        """Get a concept by ID, parsing stored metadata."""
        self.cursor.execute("SELECT metadata FROM concepts WHERE id = ?", (concept_id,))
        row = self.cursor.fetchone()
        if row and row[0]:
            return json.loads(row[0])
        return None

    def get_all_concepts(self) -> List[Dict[str, Any]]:
        """Get all concepts with full metadata."""
        self.cursor.execute("SELECT metadata FROM concepts")
        rows = self.cursor.fetchall()
        return [json.loads(row[0]) for row in rows if row and row[0]]

    def get_statistics(self) -> Dict[str, Any]:
        """Get concept count statistics."""
        self.cursor.execute("SELECT COUNT(*) FROM concepts")
        count = self.cursor.fetchone()[0]
        return {"total_concepts": count}

    def close(self):
        """Close connection (managed by KGManager)."""
        pass


if __name__ == "__main__":
    print("ConceptStore Demo")

    conn = sqlite3.connect(":memory:")
    store = ConceptStore(conn)

    concept = {
        "id": "total_revenue",
        "display_name": "Total Revenue",
        "definition": "The total amount of income generated by the sale of goods or services.",
        "domain": "finance",
        "unit": "USD",
    }

    store.add_concepts_batch([concept])
    print(f"Added concept: {concept['id']}")

    retrieved = store.get_concept_by_id(concept["id"])
    print(f"Retrieved: {retrieved['display_name']}")
    print(f"  Extra attribute 'unit': {retrieved.get('unit')}")

    all_concepts = store.get_all_concepts()
    print(f"Total concepts: {len(all_concepts)}")

    conn.close()
    print("Demo complete!")
